RENAME TABLE `jlm`.`cities` TO `jlm`.`jlm_contact_city` ;
RENAME TABLE `jlm`.`countries` TO `jlm`.`jlm_contact_country` ;
RENAME TABLE `jlm`.`addresses` TO `jlm`.`jlm_contact_address` ;

CREATE TABLE jlm_contact_association (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_company (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_corporation (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_corporationcontact (id INT AUTO_INCREMENT NOT NULL, contact_id INT DEFAULT NULL, corporation_id INT DEFAULT NULL, manager_id INT DEFAULT NULL, position VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_C1D14A97E7A1254A (contact_id), INDEX IDX_C1D14A97B2685369 (corporation_id), INDEX IDX_C1D14A97783E3463 (manager_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_contact (id INT AUTO_INCREMENT NOT NULL, address_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, discr VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_11D56661F5B7AF75 (address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_contact_phone (contact_id INT NOT NULL, phone_id INT NOT NULL, INDEX IDX_17C3A5BFE7A1254A (contact_id), UNIQUE INDEX UNIQ_17C3A5BF3B7323CB (phone_id), PRIMARY KEY(contact_id, phone_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_phone (id INT AUTO_INCREMENT NOT NULL, `label` VARCHAR(255) NOT NULL, number VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE jlm_contact_person (id INT NOT NULL, title VARCHAR(4) NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE jlm_contact_association ADD CONSTRAINT FK_14EB6F52BF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE jlm_contact_company ADD CONSTRAINT FK_12088916BF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE jlm_contact_corporation ADD CONSTRAINT FK_6D44181DBF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE jlm_contact_corporationcontact ADD CONSTRAINT FK_C1D14A97E7A1254A FOREIGN KEY (contact_id) REFERENCES jlm_contact_contact (id);
ALTER TABLE jlm_contact_corporationcontact ADD CONSTRAINT FK_C1D14A97B2685369 FOREIGN KEY (corporation_id) REFERENCES jlm_contact_corporation (id);
ALTER TABLE jlm_contact_corporationcontact ADD CONSTRAINT FK_C1D14A97783E3463 FOREIGN KEY (manager_id) REFERENCES jlm_contact_corporationcontact (id)
ALTER TABLE jlm_contact_contact ADD CONSTRAINT FK_11D56661F5B7AF75 FOREIGN KEY (address_id) REFERENCES jlm_contact_address (id);
ALTER TABLE jlm_contact_contact_phone ADD CONSTRAINT FK_17C3A5BFE7A1254A FOREIGN KEY (contact_id) REFERENCES jlm_contact_contact (id);
ALTER TABLE jlm_contact_contact_phone ADD CONSTRAINT FK_17C3A5BF3B7323CB FOREIGN KEY (phone_id) REFERENCES jlm_contact_phone (id);
ALTER TABLE jlm_contact_person ADD CONSTRAINT FK_EB478A8CBF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT FK_1483A5E9E7A1254A FOREIGN KEY (contact_id) REFERENCES jlm_contact_contact (id);
CREATE UNIQUE INDEX UNIQ_1483A5E9E7A1254A ON users (contact_id);
ALTER TABLE technicians DROP FOREIGN KEY FK_63FB4240BF396750;
ALTER TABLE technicians ADD CONSTRAINT FK_63FB4240BF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE trustees DROP FOREIGN KEY FK_A8950608BF396750;
ALTER TABLE trustees ADD CONSTRAINT FK_A8950608BF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE site_contacts DROP FOREIGN KEY FK_3F0DAAA9217BBB47;
ALTER TABLE site_contacts ADD CONSTRAINT FK_3F0DAAA9217BBB47 FOREIGN KEY (person_id) REFERENCES jlm_contact_person (id);
ALTER TABLE askquote DROP FOREIGN KEY FK_6B83768A217BBB47;
ALTER TABLE askquote ADD CONSTRAINT FK_6B83768A217BBB47 FOREIGN KEY (person_id) REFERENCES jlm_contact_person (id);
ALTER TABLE transmitters_ask DROP FOREIGN KEY FK_E9DDB4E4217BBB47;
ALTER TABLE transmitters_ask ADD CONSTRAINT FK_E9DDB4E4217BBB47 FOREIGN KEY (person_id) REFERENCES jlm_contact_person (id);
ALTER TABLE transmitters_model CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE suppliers DROP FOREIGN KEY FK_AC28B95CBF396750;
ALTER TABLE suppliers ADD CONSTRAINT FK_AC28B95CBF396750 FOREIGN KEY (id) REFERENCES jlm_contact_contact (id) ON DELETE CASCADE;
ALTER TABLE contracts CHANGE number number VARCHAR(255) NOT NULL;
ALTER TABLE quote DROP FOREIGN KEY FK_6B71CBF4176FE013;
ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4176FE013 FOREIGN KEY (contactPerson_id) REFERENCES jlm_contact_person (id);
ALTER TABLE intromodel CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE paymentmodel CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE delaymodel CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE propertymodel CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE introbillmodel CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE penaltymodel CHANGE text text LONGTEXT NOT NULL;
ALTER TABLE earlypaymentmodel CHANGE text text LONGTEXT NOT NULL
ALTER TABLE technicians DROP FOREIGN KEY FK_63FB4240BF396750;
ALTER TABLE technicians ADD contact_id INT DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE technicians ADD CONSTRAINT FK_63FB4240E7A1254A FOREIGN KEY (contact_id) REFERENCES jlm_contact_contact (id);
CREATE UNIQUE INDEX UNIQ_63FB4240E7A1254A ON technicians (contact_id);
ALTER TABLE trustees DROP FOREIGN KEY FK_A8950608BF396750;
ALTER TABLE trustees ADD contact_id INT DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE trustees ADD CONSTRAINT FK_A8950608E7A1254A FOREIGN KEY (contact_id) REFERENCES jlm_contact_contact (id);
CREATE UNIQUE INDEX UNIQ_A8950608E7A1254A ON trustees (contact_id);
ALTER TABLE suppliers DROP FOREIGN KEY FK_AC28B95CBF396750;
ALTER TABLE suppliers ADD contact_id INT DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE suppliers ADD CONSTRAINT FK_AC28B95CE7A1254A FOREIGN KEY (contact_id) REFERENCES jlm_contact_contact (id);
CREATE UNIQUE INDEX UNIQ_AC28B95CE7A1254A ON suppliers (contact_id)


