CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, person_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_1483A5E9A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_1483A5E9217BBB47 (person_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE companies (id INT AUTO_INCREMENT NOT NULL, address_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, fax VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, discr VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8244AA3AF5B7AF75 (address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE companies_contacts (company_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_7E2E05A2979B1AD6 (company_id), UNIQUE INDEX UNIQ_7E2E05A2217BBB47 (person_id), PRIMARY KEY(company_id, person_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE trustees (id INT NOT NULL, accountNumber INT NOT NULL, billingPhone VARCHAR(20) DEFAULT NULL, billingFax VARCHAR(20) DEFAULT NULL, billingEmail VARCHAR(255) DEFAULT NULL, billingAddress_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_A895060843656FE6 (billingAddress_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE doors (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, type_id INT DEFAULT NULL, street LONGTEXT NOT NULL, location VARCHAR(255) NOT NULL, googlemaps LONGTEXT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, stopped TINYINT(1) NOT NULL, INDEX IDX_5E5B762AF6BD1646 (site_id), INDEX IDX_5E5B762AC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE doors_parts (door_id INT NOT NULL, part_id INT NOT NULL, INDEX IDX_49F3F34458639EAE (door_id), INDEX IDX_49F3F3444CE34BEC (part_id), PRIMARY KEY(door_id, part_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE doors_transmitters (door_id INT NOT NULL, transmitters_id INT NOT NULL, INDEX IDX_214F836258639EAE (door_id), INDEX IDX_214F8362FA71AE84 (transmitters_id), PRIMARY KEY(door_id, transmitters_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE suppliers (id INT NOT NULL, website VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE persons (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(4) NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) NOT NULL, fixedPhone VARCHAR(20) DEFAULT NULL, mobilePhone VARCHAR(20) DEFAULT NULL, fax VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE technicians (id INT NOT NULL, internalPhone VARCHAR(20) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE products (id INT AUTO_INCREMENT NOT NULL, supplier_id INT DEFAULT NULL, category_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, reference VARCHAR(16) NOT NULL, barcode VARCHAR(255) DEFAULT NULL, unitPrice NUMERIC(10, 2) NOT NULL, purchase NUMERIC(10, 2) NOT NULL, discount_supplier SMALLINT NOT NULL, expense_ratio SMALLINT NOT NULL, shipping NUMERIC(10, 2) NOT NULL, unity VARCHAR(255) NOT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_B3BA5A5A2ADD6D8C (supplier_id), INDEX IDX_B3BA5A5A12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE transmitters (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE sites (id INT AUTO_INCREMENT NOT NULL, address_id INT DEFAULT NULL, trustee_id INT DEFAULT NULL, vat_id INT DEFAULT NULL, accession TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_BC00AA63F5B7AF75 (address_id), INDEX IDX_BC00AA63AFD45F7C (trustee_id), INDEX IDX_BC00AA63B5B63A6B (vat_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_code VARCHAR(2) DEFAULT NULL, name VARCHAR(255) NOT NULL, zip VARCHAR(20) NOT NULL, INDEX IDX_D95DB16BF026BB7C (country_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE contracts (id INT AUTO_INCREMENT NOT NULL, trustee_id INT DEFAULT NULL, door_id INT DEFAULT NULL, number VARCHAR(32) NOT NULL, complete SMALLINT NOT NULL, contract_option SMALLINT NOT NULL, begin DATETIME NOT NULL, end_warranty DATETIME DEFAULT NULL, end_contract DATETIME DEFAULT NULL, fee NUMERIC(10, 2) NOT NULL, INDEX IDX_950A973AFD45F7C (trustee_id), INDEX IDX_950A97358639EAE (door_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE site_contacts (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, person_id INT DEFAULT NULL, role VARCHAR(255) NOT NULL, INDEX IDX_3F0DAAA9F6BD1646 (site_id), INDEX IDX_3F0DAAA9217BBB47 (person_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE vat (id INT AUTO_INCREMENT NOT NULL, rate NUMERIC(3, 3) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE countries (code VARCHAR(2) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(code)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE door_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE linked_files (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, INDEX IDX_B631AFAE4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE product_category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_CDFC7356727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE addresses (id INT AUTO_INCREMENT NOT NULL, city_id INT DEFAULT NULL, street LONGTEXT DEFAULT NULL, INDEX IDX_6FCA75168BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quote_variant (id INT AUTO_INCREMENT NOT NULL, quote_id INT DEFAULT NULL, creation DATETIME NOT NULL, variant_number SMALLINT NOT NULL, intro LONGTEXT NOT NULL, payment_rules VARCHAR(255) NOT NULL, delivery_rules VARCHAR(255) NOT NULL, discount NUMERIC(10, 7) NOT NULL, state SMALLINT NOT NULL, INDEX IDX_1EAC1729DB805178 (quote_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quote (id INT AUTO_INCREMENT NOT NULL, trustee_id INT DEFAULT NULL, door_id INT DEFAULT NULL, contact_id INT DEFAULT NULL, creation DATETIME NOT NULL, trustee_name VARCHAR(255) NOT NULL, trustee_address LONGTEXT NOT NULL, number INT NOT NULL, follower VARCHAR(255) DEFAULT NULL, follower_cp VARCHAR(255) NOT NULL, door_cp LONGTEXT NOT NULL, contact_cp VARCHAR(255) NOT NULL, vat NUMERIC(3, 3) NOT NULL, vat_transmitter NUMERIC(3, 3) NOT NULL, INDEX IDX_6B71CBF4AFD45F7C (trustee_id), INDEX IDX_6B71CBF458639EAE (door_id), INDEX IDX_6B71CBF4E7A1254A (contact_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quote_lines (id INT AUTO_INCREMENT NOT NULL, variant_id INT DEFAULT NULL, product_id INT DEFAULT NULL, position SMALLINT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, designation VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, show_description TINYINT(1) DEFAULT NULL, is_transmitter TINYINT(1) DEFAULT NULL, quantity INT NOT NULL, purchasePrice NUMERIC(10, 2) NOT NULL, discount_supplier NUMERIC(10, 7) NOT NULL, expense_ratio NUMERIC(10, 7) NOT NULL, shipping NUMERIC(10, 2) NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, discount NUMERIC(10, 7) NOT NULL, vat NUMERIC(3, 3) NOT NULL, INDEX IDX_42FE01F73B69A9AF (variant_id), INDEX IDX_42FE01F74584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE intromodel (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE delaymodel (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE paymentmodel (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting (id INT AUTO_INCREMENT NOT NULL, creation DATETIME NOT NULL, place LONGTEXT NOT NULL, reason LONGTEXT NOT NULL, actionType VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting_interventions (id INT NOT NULL, door_id INT DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, contact_phones LONGTEXT DEFAULT NULL, contact_email LONGTEXT DEFAULT NULL, report LONGTEXT DEFAULT NULL, comments LONGTEXT DEFAULT NULL, priority SMALLINT NOT NULL, closed TINYINT(1) NOT NULL, INDEX IDX_291B3FA258639EAE (door_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting_receiver (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE work_objectives (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting_works (id INT NOT NULL, quote_id INT DEFAULT NULL, category_id INT DEFAULT NULL, objective_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_57D2710BDB805178 (quote_id), INDEX IDX_57D2710B12469DE2 (category_id), INDEX IDX_57D2710B73484933 (objective_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shift_technician (id INT AUTO_INCREMENT NOT NULL, shifting_id INT DEFAULT NULL, technician_id INT DEFAULT NULL, creation DATETIME NOT NULL, begin DATETIME DEFAULT NULL, end DATETIME DEFAULT NULL, INDEX IDX_C6FBA26761CEF47 (shifting_id), INDEX IDX_C6FBA267E6C5D496 (technician_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE fixing_dues (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE fixing_dones (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting_fixing (id INT NOT NULL, due_id INT DEFAULT NULL, done_id INT DEFAULT NULL, order_number INT DEFAULT NULL, INDEX IDX_42CE6C07866D9843 (due_id), INDEX IDX_42CE6C07A8CDD838 (done_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting_maintenance (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE shifting_equipments (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE work_categories (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE users ADD CONSTRAINT FK_1483A5E9217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE companies ADD CONSTRAINT FK_8244AA3AF5B7AF75 FOREIGN KEY (address_id) REFERENCES addresses (id);
ALTER TABLE companies_contacts ADD CONSTRAINT FK_7E2E05A2979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE companies_contacts ADD CONSTRAINT FK_7E2E05A2217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE trustees ADD CONSTRAINT FK_A895060843656FE6 FOREIGN KEY (billingAddress_id) REFERENCES addresses (id);
ALTER TABLE trustees ADD CONSTRAINT FK_A8950608BF396750 FOREIGN KEY (id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE doors ADD CONSTRAINT FK_5E5B762AF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id);
ALTER TABLE doors ADD CONSTRAINT FK_5E5B762AC54C8C93 FOREIGN KEY (type_id) REFERENCES door_types (id);
ALTER TABLE doors_parts ADD CONSTRAINT FK_49F3F34458639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE doors_parts ADD CONSTRAINT FK_49F3F3444CE34BEC FOREIGN KEY (part_id) REFERENCES products (id);
ALTER TABLE doors_transmitters ADD CONSTRAINT FK_214F836258639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE doors_transmitters ADD CONSTRAINT FK_214F8362FA71AE84 FOREIGN KEY (transmitters_id) REFERENCES transmitters (id);
ALTER TABLE suppliers ADD CONSTRAINT FK_AC28B95CBF396750 FOREIGN KEY (id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE technicians ADD CONSTRAINT FK_63FB4240BF396750 FOREIGN KEY (id) REFERENCES persons (id) ON DELETE CASCADE;
ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id);
ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES product_category (id);
ALTER TABLE transmitters ADD CONSTRAINT FK_C5000497BF396750 FOREIGN KEY (id) REFERENCES products (id) ON DELETE CASCADE;
ALTER TABLE sites ADD CONSTRAINT FK_BC00AA63F5B7AF75 FOREIGN KEY (address_id) REFERENCES addresses (id);
ALTER TABLE sites ADD CONSTRAINT FK_BC00AA63AFD45F7C FOREIGN KEY (trustee_id) REFERENCES trustees (id);
ALTER TABLE sites ADD CONSTRAINT FK_BC00AA63B5B63A6B FOREIGN KEY (vat_id) REFERENCES vat (id);
ALTER TABLE cities ADD CONSTRAINT FK_D95DB16BF026BB7C FOREIGN KEY (country_code) REFERENCES countries (code);
ALTER TABLE contracts ADD CONSTRAINT FK_950A973AFD45F7C FOREIGN KEY (trustee_id) REFERENCES trustees (id);
ALTER TABLE contracts ADD CONSTRAINT FK_950A97358639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE site_contacts ADD CONSTRAINT FK_3F0DAAA9F6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id);
ALTER TABLE site_contacts ADD CONSTRAINT FK_3F0DAAA9217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id);
ALTER TABLE linked_files ADD CONSTRAINT FK_B631AFAE4584665A FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE product_category ADD CONSTRAINT FK_CDFC7356727ACA70 FOREIGN KEY (parent_id) REFERENCES product_category (id);
ALTER TABLE addresses ADD CONSTRAINT FK_6FCA75168BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id);
ALTER TABLE quote_variant ADD CONSTRAINT FK_1EAC1729DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id);
ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4AFD45F7C FOREIGN KEY (trustee_id) REFERENCES trustees (id);
ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF458639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4E7A1254A FOREIGN KEY (contact_id) REFERENCES site_contacts (id);
ALTER TABLE quote_lines ADD CONSTRAINT FK_42FE01F73B69A9AF FOREIGN KEY (variant_id) REFERENCES quote_variant (id);
ALTER TABLE quote_lines ADD CONSTRAINT FK_42FE01F74584665A FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE shifting_interventions ADD CONSTRAINT FK_291B3FA258639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE shifting_interventions ADD CONSTRAINT FK_291B3FA2BF396750 FOREIGN KEY (id) REFERENCES shifting (id) ON DELETE CASCADE;
ALTER TABLE shifting_receiver ADD CONSTRAINT FK_FF9EDF75BF396750 FOREIGN KEY (id) REFERENCES shifting (id) ON DELETE CASCADE;
ALTER TABLE shifting_works ADD CONSTRAINT FK_57D2710BDB805178 FOREIGN KEY (quote_id) REFERENCES quote (id);
ALTER TABLE shifting_works ADD CONSTRAINT FK_57D2710B12469DE2 FOREIGN KEY (category_id) REFERENCES work_categories (id);
ALTER TABLE shifting_works ADD CONSTRAINT FK_57D2710B73484933 FOREIGN KEY (objective_id) REFERENCES work_objectives (id);
ALTER TABLE shifting_works ADD CONSTRAINT FK_57D2710BBF396750 FOREIGN KEY (id) REFERENCES shifting (id) ON DELETE CASCADE;
ALTER TABLE shift_technician ADD CONSTRAINT FK_C6FBA26761CEF47 FOREIGN KEY (shifting_id) REFERENCES shifting (id);
ALTER TABLE shift_technician ADD CONSTRAINT FK_C6FBA267E6C5D496 FOREIGN KEY (technician_id) REFERENCES technicians (id);
ALTER TABLE shifting_fixing ADD CONSTRAINT FK_42CE6C07866D9843 FOREIGN KEY (due_id) REFERENCES fixing_dues (id);
ALTER TABLE shifting_fixing ADD CONSTRAINT FK_42CE6C07A8CDD838 FOREIGN KEY (done_id) REFERENCES fixing_dones (id);
ALTER TABLE shifting_fixing ADD CONSTRAINT FK_42CE6C07BF396750 FOREIGN KEY (id) REFERENCES shifting (id) ON DELETE CASCADE;
ALTER TABLE shifting_maintenance ADD CONSTRAINT FK_C7BB1DB8BF396750 FOREIGN KEY (id) REFERENCES shifting (id) ON DELETE CASCADE;
ALTER TABLE shifting_equipments ADD CONSTRAINT FK_E85D4703BF396750 FOREIGN KEY (id) REFERENCES shifting (id) ON DELETE CASCADE;
INSERT INTO `vat` (`id`, `rate`) VALUES
(1, 0.196),
(2, 0.070);

INSERT INTO `countries` (`code`, `name`) VALUES
('FR', 'France');

INSERT INTO `door_types` (`id`, `name`) VALUES
(1, 'Barrière levante'),
(2, 'Portail battant à 1 ventail'),
(3, 'Portail battant à 2 ventaux'),
(4, 'Portail coulissant'),
(5, 'Porte accordéon'),
(6, 'Porte basculante'),
(7, 'Porte pivotante à 1 ventail'),
(8, 'Porte pivotante à 2 ventaux'),
(9, 'Portillon');


INSERT INTO `persons` (`id`, `title`, `firstName`, `lastName`, `fixedPhone`, `mobilePhone`, `fax`, `email`, `discr`) VALUES
(1, 'M.', 'Jean-Louis', 'Martinez', '8000', '0609103969', NULL, 'jean-louis.martinez@jlm-entreprise.fr', 'person'),
(2, 'Mme', 'Nadine', 'Martinez', '8002', '0608494350', NULL, 'nadine.martinez@jlm-entreprise.fr', 'person'),
(3, 'M.', 'Yohann', 'Martinez', '8001', '0626066410', NULL, 'yohann.martinez@jlm-entreprise.fr', 'person'),
(4, 'M.', 'Oscar', 'Cantuarias Elizalde', '8004', '0689536095', NULL, NULL, 'technician'),
(5, 'M.', 'Christophe', 'Vairreto', '8005', '0684789430', NULL, NULL, 'technician'),
(6, 'M.', 'Cyrille', 'Frelat', '8006', '0682533537', NULL, NULL, 'technician'),
(7, 'M.', 'Emmanuel', 'Bernaszuk', NULL, '0678354065', NULL, 'emmanuel.bernaszuk@jlm-entreprise.fr', 'person'),
(8, 'Mlle', 'Aurélie', 'Costalat', NULL, '0637046093', NULL, 'aurelie.costalat@jlm-entreprise.fr', 'person');

INSERT INTO `technicians` (`id`, `internalPhone`) VALUES
(4, '8004'),
(5, '8005'),
(6, '8006');

INSERT INTO `users` (`id`, `person_id`, `username`, `username_canonical`, `email`, `email_canonical`, `enabled`, `salt`, `password`, `last_login`, `locked`, `expired`, `expires_at`, `confirmation_token`, `password_requested_at`, `roles`, `credentials_expired`, `credentials_expire_at`) VALUES
(1, 7, 'kwizer', 'kwizer', 'emmanuel.bernaszuk@jlm-entreprise.fr', 'emmanuel.bernaszuk@jlm-entreprise.fr', 1, 'lxodjjrzhmo0soo4o48w4c8wcckc408', '3Vnn3P7Rh5pYnvJ44rn6NLkM1o7LtWmeyYG191MS0oiwytalyFt7xRXgCszFbUJSjWjGmRN11n4UkXuTU/Ti4Q==', '2012-11-23 09:40:11', 0, 0, NULL, NULL, NULL, 'a:1:{i:0;s:10:"ROLE_ADMIN";}', 0, NULL);

INSERT INTO `fixing_dones` (`id`, `name`) VALUES
(1, 'Remplacer'),
(2, 'Réparer'),
(3, 'Mise à l''arrêt'),
(4, 'Graissage, essais');

INSERT INTO `fixing_dues` (`id`, `name`) VALUES
(1, 'Usure'),
(2, 'Dégradation'),
(3, 'Malveillance'),
(4, 'Disfonctionnement / RAS');


INSERT INTO `product_category` (`id`, `parent_id`, `name`) VALUES
(1, NULL, 'Emetteurs'),
(2, NULL, 'Service');


INSERT INTO `work_categories` (`id`, `name`) VALUES
(1, 'Petits travaux / SAV'),
(2, 'Rénovation'),
(3, 'Neuf'),
(4, 'Réparation');



INSERT INTO `work_objectives` (`id`, `name`) VALUES
(1, 'Mise en service'),
(2, 'Levée de réserve');