ALTER TABLE doors ADD last_maintenance DATE DEFAULT NULL
CREATE TABLE task (id INT AUTO_INCREMENT NOT NULL, todo LONGTEXT NOT NULL, url LONGTEXT NOT NULL, closed TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE bill (id INT AUTO_INCREMENT NOT NULL, trustee_id INT DEFAULT NULL, door_id INT DEFAULT NULL, creation DATETIME NOT NULL, trustee_name VARCHAR(255) NOT NULL, trustee_address LONGTEXT NOT NULL, number INT NOT NULL, door_cp LONGTEXT NOT NULL, INDEX IDX_7A2119E3AFD45F7C (trustee_id), INDEX IDX_7A2119E358639EAE (door_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE bill ADD CONSTRAINT FK_7A2119E3AFD45F7C FOREIGN KEY (trustee_id) REFERENCES trustees (id);
ALTER TABLE bill ADD CONSTRAINT FK_7A2119E358639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE shifting_interventions ADD officeAction_id INT DEFAULT NULL;
ALTER TABLE shifting_interventions ADD CONSTRAINT FK_291B3FA2A9A54B29 FOREIGN KEY (officeAction_id) REFERENCES task (id);
CREATE UNIQUE INDEX UNIQ_291B3FA2A9A54B29 ON shifting_interventions (officeAction_id)
ALTER TABLE task ADD open DATETIME NOT NULL, ADD close DATETIME NOT NULL, DROP closed
CREATE TABLE tasktype (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE task ADD door_id INT DEFAULT NULL, ADD type_id INT DEFAULT NULL, ADD url_source LONGTEXT DEFAULT NULL, ADD url_action LONGTEXT DEFAULT NULL, CHANGE url place LONGTEXT NOT NULL;
ALTER TABLE task ADD CONSTRAINT FK_527EDB2558639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE task ADD CONSTRAINT FK_527EDB25C54C8C93 FOREIGN KEY (type_id) REFERENCES tasktype (id);
CREATE INDEX IDX_527EDB2558639EAE ON task (door_id);
CREATE INDEX IDX_527EDB25C54C8C93 ON task (type_id);
INSERT INTO `jlm`.`tasktype` (`id`, `text`) VALUES (NULL, 'Facturer'), (NULL, 'Devis'), (NULL, 'Commander matériel'), (NULL, 'Contacter client'), (NULL, 'Ne rien faire');
ALTER TABLE task CHANGE close close DATETIME DEFAULT NULL
ALTER TABLE shifting_works DROP INDEX UNIQ_57D2710BDB805178, ADD INDEX IDX_57D2710BDB805178 (quote_id)
