ALTER TABLE persons ADD address LONGTEXT NOT NULL;
ALTER TABLE persons ADD address_id INT DEFAULT NULL, DROP address;
ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D3F5B7AF75 FOREIGN KEY (address_id) REFERENCES addresses (id);
CREATE UNIQUE INDEX UNIQ_A25CC7D3F5B7AF75 ON persons (address_id);
