CREATE TABLE orders (id INT AUTO_INCREMENT NOT NULL, quote_id INT DEFAULT NULL, creation DATETIME NOT NULL, place LONGTEXT NOT NULL, state INT NOT NULL, INDEX IDX_E52FFDEEDB805178 (quote_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE order_lines (id INT AUTO_INCREMENT NOT NULL, position SMALLINT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, designation VARCHAR(255) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEDB805178 FOREIGN KEY (quote_id) REFERENCES quote_variant (id);
ALTER TABLE order_lines ADD order_id INT DEFAULT NULL;
ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id);
CREATE INDEX IDX_CC9FF86B8D9F6D38 ON order_lines (order_id);
ALTER TABLE orders ADD door_id INT DEFAULT NULL;
ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE58639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
CREATE INDEX IDX_E52FFDEE58639EAE ON orders (door_id);
CREATE TABLE transmitter_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE products DROP discr;
ALTER TABLE `doors_transmitters` DROP FOREIGN KEY `FK_214F8362FA71AE84` ,
ADD FOREIGN KEY ( `transmitters_id` ) REFERENCES `jlm`.`transmitter_types` (
`id`
) ON DELETE RESTRICT ON UPDATE RESTRICT ;
DROP TABLE `transmitters`;
