ALTER TABLE `doors` CHANGE `transmitter_code` `observations` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE sites ADD lodge_id INT DEFAULT NULL, ADD observations LONGTEXT DEFAULT NULL;
ALTER TABLE sites ADD CONSTRAINT FK_BC00AA63B217AB93 FOREIGN KEY (lodge_id) REFERENCES addresses (id);
CREATE UNIQUE INDEX UNIQ_BC00AA63B217AB93 ON sites (lodge_id);
