CREATE TABLE door_stops (id INT AUTO_INCREMENT NOT NULL, door_id INT DEFAULT NULL, begin DATETIME NOT NULL, end DATETIME NOT NULL, reason VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, INDEX IDX_C82F338758639EAE (door_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE door_stops ADD CONSTRAINT FK_C82F338758639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE door_stops CHANGE end end DATETIME DEFAULT NULL;

