ALTER TABLE doors ADD last_maintenance DATE DEFAULT NULL
CREATE TABLE task (id INT AUTO_INCREMENT NOT NULL, todo LONGTEXT NOT NULL, url LONGTEXT NOT NULL, closed TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE bill (id INT AUTO_INCREMENT NOT NULL, trustee_id INT DEFAULT NULL, door_id INT DEFAULT NULL, creation DATETIME NOT NULL, trustee_name VARCHAR(255) NOT NULL, trustee_address LONGTEXT NOT NULL, number INT NOT NULL, door_cp LONGTEXT NOT NULL, INDEX IDX_7A2119E3AFD45F7C (trustee_id), INDEX IDX_7A2119E358639EAE (door_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE bill ADD CONSTRAINT FK_7A2119E3AFD45F7C FOREIGN KEY (trustee_id) REFERENCES trustees (id);
ALTER TABLE bill ADD CONSTRAINT FK_7A2119E358639EAE FOREIGN KEY (door_id) REFERENCES doors (id);
ALTER TABLE shifting_interventions ADD officeAction_id INT DEFAULT NULL;
ALTER TABLE shifting_interventions ADD CONSTRAINT FK_291B3FA2A9A54B29 FOREIGN KEY (officeAction_id) REFERENCES task (id);
CREATE UNIQUE INDEX UNIQ_291B3FA2A9A54B29 ON shifting_interventions (officeAction_id)
ALTER TABLE task ADD open DATETIME NOT NULL, ADD close DATETIME NOT NULL, DROP closed
