<?php

namespace JLM\TransmitterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributionRepository extends EntityRepository
{
	public function getById($id)
	{
		$qb = $this->createQueryBuilder('a')
			->select('a,b,c,d,e,f,g,h,i,j,k')
			->leftJoin('a.ask','b')
			->leftJoin('b.site','c')
			->leftJoin('c.address','d')
			->leftJoin('d.city','e')
			->leftJoin('a.transmitters','f')
			->leftJoin('f.userGroup','g')
			->leftJoin('f.model','h')
			->leftJoin('c.userGroups','i')
			->leftJoin('f.replace','j')
			->leftJoin('f.replacedTransmitter','k')
			->where('a.id = ?1')
			->setParameter(1,$id)
		;
		$results = $qb->getQuery()->getArrayResult();
		$result = $results[0];
		foreach ($result['transmitters'] as $index => $t)
		{
			$result['transmitters'][$index]['endGuaranteeDate'] = \DateTime::createFromFormat('my',$t['guarantee'])->add(new \DateInterval('P2Y'));
		}
		return $result;
	}
}
