<?php

/*
 * This file is part of the JLMCommerceBundle package.
 *
 * (c) Emmanuel Bernaszuk <emmanuel.bernaszuk@kw12er.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace JLM\CommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TextModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Emmanuel Bernaszuk <emmanuel.bernaszuk@kw12er.com>
 */
class TextModelRepository extends EntityRepository
{
	public function searchResult($query, $limit = 8)
	{
		
		$results = $this->createQueryBuilder('m')
	   		->where('m.text LIKE :term')
	   		->setParameter('term','%'.$query.'%')
	   		->getQuery()
	   		->getResult();
   		$out = array();
   		foreach($results as $result)
   		{
   			$out[] = $result->getText();
   		}
   		
   		return $out;
	}
}