<?php

namespace JLM\OfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodingRepository extends EntityRepository
{
	public function getTotal()
	{
		$qb = $this->createQueryBuilder('q')
		->select('COUNT(q)');
		
		return (int) $qb->getQuery()
		->getSingleScalarResult();
	}
}