<?php

namespace JLM\OfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IntroModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntroModelRepository extends EntityRepository
{
	public function searchResult($query, $limit = 8)
	{
		
		$results = $this->createQueryBuilder('m')
	   		->where('m.text LIKE :term')
	   		->setParameter('term','%'.$query.'%')
	   		->getQuery()
	   		->getResult();
   		$out = array();
   		foreach($results as $result)
   			$out[] = $result->getText();
   		return $out;
	}
}