<?php

namespace JLM\OfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteVariantRepository extends EntityRepository
{
	public function getCount(Quote $quote)
	{
		$qb = $this->createQueryBuilder('q')
		->select('COUNT(q)')
		->where('q.quote = :quote')
		->setParameter('quote',$quote);
		
		return (int) $qb->getQuery()
		->getSingleScalarResult();
	}
	
	public function find($id, $lockMode = LockMode::NONE, $lockVersion = null)
	{
		$qb = $this->createQueryBuilder('v')
		->select('v,q')
		->leftJoin('v.quote','q')
		->where('v.quote = :quote')
		->setParameter('quote',$quote);
		
		return (int) $qb->getQuery()
		->getSingleResult();
	}
}