<?php

namespace JLM\ModelBundle\Entity;

use JLM\DefaultBundle\Entity\SearchRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends SearchRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getSearchQb()
	{
		return $this->createQueryBuilder('a');
	}
	
	/**
	 * {@inheritdoc}
	 */
	protected function getSearchParams()
	{
		return array('a.firstName','a.lastName');
	}
	
	public function match($query)
	{
		return $this->search($query);
	}
	
	public function searchResult($query, $limit = 8)
	{
		$res = $this->search($query);
		$r2 = array();
		foreach ($res as $r)
		{
			$r2[] = array(
					'id'=>''.$r->getId(),
					'label'=>''.$r,
			);
		}
		return $r2;
	}
}