<?php

namespace JLM\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
	public function search($query)
	{
		$qb = $this->createQueryBuilder('a')
		->where('a.firstName LIKE :query')
		->orWhere('a.lastName LIKE :query')
		->setParameter('query', '%'.$query.'%')
		;
		
		return $qb->getQuery()->getResult();
	}
	
	public function match($query)
	{
		return $this->search($query);
	}
	
	public function searchResult($query, $limit = 8)
	{
		$res = $this->search($query);
		$r2 = array();
		foreach ($res as $r)
		{
			$r2[] = array(
					'id'=>''.$r->getId(),
					'label'=>''.$r,
			);
		}
		return $r2;
	}
}