<?php

namespace JLM\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
	public function searchResult($query, $limit = 8)
	{
		
		$qb = $this->createQueryBuilder('s')
			   ->leftJoin('s.address','a')
			   ->leftJoin('a.city','c')
			   ->where('a.street LIKE :querystreet')
			   ->orWhere('c.name LIKE :querycity')
			   ->setParameter('querystreet', '%'.$query.'%')
			   ->setParameter('querycity', $query.'%')
		;

		$res = $qb->getQuery()->getResult();
		
		$r2 = array();
		foreach ($res as $r)
		{
			$r2[] = ''.$r;
		}
		return $r2;
	}
	
	public function match($string)
	{
		if (preg_match('#^(.+) - (.+)$#',$string,$matches))
		{
			$qb = $this->createQueryBuilder('s')
				->leftJoin('s.address','a')
				->leftJoin('a.city','c')
				->where('a.street LIKE :querystreet')
				->andWhere('c.name LIKE :querycity')
				->setParameter('querystreet', $matches[2])
				->setParameter('querycity', $matches[1])
				;
			$res = $qb->getQuery()->getResult();
			if ($res)
				return $res[0];
		}
		else
			return null;
	}
}