<?php

namespace JLM\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrusteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrusteeRepository extends EntityRepository
{
	public function search($query)
	{
		$qb = $this->createQueryBuilder('c')
		->where('c.name LIKE :query')
		->setParameter('query', $query.'%')
		;
		return $qb->getQuery()->getResult();
	}
	
	public function searchResult($query, $limit = 8)
	{

		$res = $this->search($query);
		$r2 = array();

		foreach ($res as $r)
		{
			$r2[] = array(
					'trustee'       => ''.$r->getId(),
					'label'         => ''.$r,
					'trusteeAddress'=> ($r->getBillingAddress() === null) ? ''.$r->getAddress() : ''.$r->getBillingAddress(),
			);
		}
		return $r2;
	}
	
	public function getTotal()
	{
		$qb = $this->createQueryBuilder('s')
		->select('COUNT(s)');
	
		return (int) $qb->getQuery()
		->getSingleScalarResult();
	}
}