<?php

namespace JLM\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrusteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrusteeRepository extends EntityRepository
{
	public function searchResult($query, $limit = 8)
	{
		$qb = $this->createQueryBuilder('c')
			   ->where('c.name LIKE :query')
			   ->setParameter('query', $query.'%')
		;
		$res = $qb->getQuery()->getResult();
		$r2 = array();
		foreach ($res as $r)
			$r2[] = ''.$r;
		return $r2;
	}
}