<?php

namespace JLM\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	public function searchResult($query, $limit = 8)
	{
		$qb = $this->createQueryBuilder('c')
			   ->where('c.zip LIKE :query')
			   ->orWhere('c.name LIKE :query')
			   ->setParameter('query', $query.'%')
		;
		$res = $qb->getQuery()->getResult();
		$r2 = array();
		foreach ($res as $r)
		{
			$r2[] = ''.$r;
		}
		return $r2;
	}
}