<?php

namespace JLM\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteContactRepository extends EntityRepository
{
    public function searchResult($query, $limit = 8)
    {
        
        $qb = $this->createQueryBuilder('s')
               ->leftjoin('s.site', 't')
               ->leftjoin('t.doors', 'd')
               ->where('d.id = :query')
               ->setParameter('query', $query)
        ;

        $res = $qb->getQuery()->getResult();
        
        $r2 = [];
        foreach ($res as $r) {
            $phones = '';
            $phones = $r->getPerson()->getMobilePhone();
            if ($phones != '') {
                $phones .= chr(10);
            }
            $phones .= $r->getPerson()->getFixedPhone();
            
            $r2[] = [
                'label'=> $r->getPerson().' ('.$r->getRole().')',
                'name' => $r->getPerson().'',
                'phones' => $phones,
                'email' => $r->getPerson()->getEmail().'',
                'id'=> $r->getId()
            ];
        }
        return $r2;
    }
}
